[build]
  command = "npm run prerender"
  functions = "./functions"
  publish = "dist/serverless-stripe/browser"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
